version: "2"

services:

  backend: #name of the second service
    build: backend # specify the directory of the Dockerfile
    restart: always
#    environment:
#      - VIRTUAL_HOST=
#      - VIRTUAL_PORT=5000
#      - LETSENCRYPT_HOST=
#      - LETSENCRYPT_EMAIL=

    networks:
      - backend
      - frontend
    links:
      - database
    ports:
      - 5000:5000


  database: # name of the third service
    image: mongo:5.0  # specify image to build container from
    restart: always
    ports:
      - "27017:27017" # specify port forewarding
    networks:
      - backend
    volumes:
      - ./mongodata:/db/data


  frontend:
    container_name: frontend
    build: frontend
    restart: always
#    volumes:
#      - '.:/app'
#      - 'frontend/app/node_modules'
#    environment:
#      - VIRTUAL_HOST=
#      - VIRTUAL_PORT=3000
#      - LETSENCRYPT_HOST=platform.withu.studio
#      - LETSENCRYPT_EMAIL=support@withu.studio
    ports:
      - 3000:3000
    networks:
      - frontend

volumes:
  db-data:

networks:
  backend:
  frontend:
